collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8799283
color:
  saturation: 0.5018485
  brandStrength: 0.5035842
  lightness: 0.6946132
  brandColors:
    - '#D87791'
    - '#271630'
    - '#FFC6B3'
    - '#6E4165'
  rhythmicContrast: 0.6354206
layout_spectrum: 0.0952331
name: Neivy
