layout_spectrum: 0.0952331
color:
  saturation: 0.5018485
  lightness: 0.6946132
  brandStrength: 0.5035842
  brandColors:
    - '#39374C'
    - '#6E646E'
    - '#D7D6D0'
    - '#FBF8F2'
  rhythmicContrast: 0.6354206
typography_spectrum: 0.8799283
name: Neivy
