layout_spectrum: 0.0952331
typography_spectrum: 0.971706
color:
  saturation: 0.5018485
  lightness: 0.6946132
  brandStrength: 0.4234145
  rhythmicContrast: 0.6354206
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Neivy
